use_frameworks!

target 'TKLogger-iOS_Example' do
  
  pod 'SnapKit',        :git => 'http://gitee.com/shper/SnapKit.git',     :branch => 'release_5.0.1.x'
  
  pod 'TKLogger', :path => '../'

  target 'TKLogger-iOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
